kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    web: tier
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      web: tier
  template:
    metadata:
      labels:
        app: nginx
        web: tier
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .values.deployment.imageVersion }}
        ports:
        - containerPort: 80